# Generated by Django 5.2 on 2025-04-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_pub',
            new_name='data_plub',
        ),
    ]
